/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace diagnostic_msgs
{
    public sealed class DiagnosticStatus : LCM.LCM.LCMEncodable
    {
        public int values_length;
        public sbyte level;
        public String name;
        public String message;
        public String hardware_id;
        public diagnostic_msgs.KeyValue[] values;
 
        public DiagnosticStatus()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x3e3fb00c69778dfbL;
 
        public const int OK = 0;
        public const int WARN = 1;
        public const int ERROR = 2;
        public const int STALE = 3;

        static DiagnosticStatus()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("diagnostic_msgs.DiagnosticStatus"))
                return 0L;
 
            classes.Add("diagnostic_msgs.DiagnosticStatus");
            ulong hash = LCM_FINGERPRINT_BASE
                 + diagnostic_msgs.KeyValue._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.values_length); 
 
            outs.Write(this.level); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.name); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.message); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.hardware_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            for (int a = 0; a < this.values_length; a++) {
                this.values[a]._encodeRecursive(outs); 
            }
 
        }
 
        public DiagnosticStatus(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public DiagnosticStatus(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static diagnostic_msgs.DiagnosticStatus _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            diagnostic_msgs.DiagnosticStatus o = new diagnostic_msgs.DiagnosticStatus();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.values_length = ins.ReadInt32();
 
            this.level = ins.ReadSByte();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.name = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.message = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.hardware_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.values = new diagnostic_msgs.KeyValue[(int) values_length];
            for (int a = 0; a < this.values_length; a++) {
                this.values[a] = diagnostic_msgs.KeyValue._decodeRecursiveFactory(ins);
            }
 
        }
 
        public diagnostic_msgs.DiagnosticStatus Copy()
        {
            diagnostic_msgs.DiagnosticStatus outobj = new diagnostic_msgs.DiagnosticStatus();
            outobj.values_length = this.values_length;
 
            outobj.level = this.level;
 
            outobj.name = this.name;
 
            outobj.message = this.message;
 
            outobj.hardware_id = this.hardware_id;
 
            outobj.values = new diagnostic_msgs.KeyValue[(int) values_length];
            for (int a = 0; a < this.values_length; a++) {
                outobj.values[a] = this.values[a].Copy();
            }
 
            return outobj;
        }
    }
}

