/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace diagnostic_msgs
{
    public sealed class DiagnosticArray : LCM.LCM.LCMEncodable
    {
        public int status_length;
        public std_msgs.Header header;
        public diagnostic_msgs.DiagnosticStatus[] status;
 
        public DiagnosticArray()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0163c308c500b94dL;
 
        static DiagnosticArray()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("diagnostic_msgs.DiagnosticArray"))
                return 0L;
 
            classes.Add("diagnostic_msgs.DiagnosticArray");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + diagnostic_msgs.DiagnosticStatus._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.status_length); 
 
            this.header._encodeRecursive(outs); 
 
            for (int a = 0; a < this.status_length; a++) {
                this.status[a]._encodeRecursive(outs); 
            }
 
        }
 
        public DiagnosticArray(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public DiagnosticArray(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static diagnostic_msgs.DiagnosticArray _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            diagnostic_msgs.DiagnosticArray o = new diagnostic_msgs.DiagnosticArray();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.status_length = ins.ReadInt32();
 
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.status = new diagnostic_msgs.DiagnosticStatus[(int) status_length];
            for (int a = 0; a < this.status_length; a++) {
                this.status[a] = diagnostic_msgs.DiagnosticStatus._decodeRecursiveFactory(ins);
            }
 
        }
 
        public diagnostic_msgs.DiagnosticArray Copy()
        {
            diagnostic_msgs.DiagnosticArray outobj = new diagnostic_msgs.DiagnosticArray();
            outobj.status_length = this.status_length;
 
            outobj.header = this.header.Copy();
 
            outobj.status = new diagnostic_msgs.DiagnosticStatus[(int) status_length];
            for (int a = 0; a < this.status_length; a++) {
                outobj.status[a] = this.status[a].Copy();
            }
 
            return outobj;
        }
    }
}

