/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace nav_msgs
{
    public sealed class OccupancyGrid : LCM.LCM.LCMEncodable
    {
        public int data_length;
        public std_msgs.Header header;
        public nav_msgs.MapMetaData info;
        public sbyte[] data;
 
        public OccupancyGrid()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x9e67f3f149308d87L;
 
        static OccupancyGrid()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("nav_msgs.OccupancyGrid"))
                return 0L;
 
            classes.Add("nav_msgs.OccupancyGrid");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + nav_msgs.MapMetaData._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.data_length); 
 
            this.header._encodeRecursive(outs); 
 
            this.info._encodeRecursive(outs); 
 
            for (int a = 0; a < this.data_length; a++) {
                outs.Write(this.data[a]); 
            }
 
        }
 
        public OccupancyGrid(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public OccupancyGrid(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static nav_msgs.OccupancyGrid _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            nav_msgs.OccupancyGrid o = new nav_msgs.OccupancyGrid();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.data_length = ins.ReadInt32();
 
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.info = nav_msgs.MapMetaData._decodeRecursiveFactory(ins);
 
            this.data = new sbyte[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                this.data[a] = ins.ReadSByte();
            }
 
        }
 
        public nav_msgs.OccupancyGrid Copy()
        {
            nav_msgs.OccupancyGrid outobj = new nav_msgs.OccupancyGrid();
            outobj.data_length = this.data_length;
 
            outobj.header = this.header.Copy();
 
            outobj.info = this.info.Copy();
 
            outobj.data = new sbyte[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                outobj.data[a] = this.data[a];
            }
 
            return outobj;
        }
    }
}

