/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace nav_msgs
{
    public sealed class Odometry : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public String child_frame_id;
        public geometry_msgs.PoseWithCovariance pose;
        public geometry_msgs.TwistWithCovariance twist;
 
        public Odometry()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x97f82279756d9d18L;
 
        static Odometry()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("nav_msgs.Odometry"))
                return 0L;
 
            classes.Add("nav_msgs.Odometry");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.PoseWithCovariance._hashRecursive(classes)
                 + geometry_msgs.TwistWithCovariance._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            this.header._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.child_frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            this.pose._encodeRecursive(outs); 
 
            this.twist._encodeRecursive(outs); 
 
        }
 
        public Odometry(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Odometry(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static nav_msgs.Odometry _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            nav_msgs.Odometry o = new nav_msgs.Odometry();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.child_frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.pose = geometry_msgs.PoseWithCovariance._decodeRecursiveFactory(ins);
 
            this.twist = geometry_msgs.TwistWithCovariance._decodeRecursiveFactory(ins);
 
        }
 
        public nav_msgs.Odometry Copy()
        {
            nav_msgs.Odometry outobj = new nav_msgs.Odometry();
            outobj.header = this.header.Copy();
 
            outobj.child_frame_id = this.child_frame_id;
 
            outobj.pose = this.pose.Copy();
 
            outobj.twist = this.twist.Copy();
 
            return outobj;
        }
    }
}

