/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class AccelWithCovariance : LCM.LCM.LCMEncodable
    {
        public geometry_msgs.Accel accel;
        public double[] covariance;
 
        public AccelWithCovariance()
        {
            covariance = new double[36];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x545f576dfe97951dL;
 
        static AccelWithCovariance()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.AccelWithCovariance"))
                return 0L;
 
            classes.Add("geometry_msgs.AccelWithCovariance");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Accel._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.accel._encodeRecursive(outs); 
 
            for (int a = 0; a < 36; a++) {
                outs.Write(this.covariance[a]); 
            }
 
        }
 
        public AccelWithCovariance(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public AccelWithCovariance(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.AccelWithCovariance _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.AccelWithCovariance o = new geometry_msgs.AccelWithCovariance();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.accel = geometry_msgs.Accel._decodeRecursiveFactory(ins);
 
            this.covariance = new double[(int) 36];
            for (int a = 0; a < 36; a++) {
                this.covariance[a] = ins.ReadDouble();
            }
 
        }
 
        public geometry_msgs.AccelWithCovariance Copy()
        {
            geometry_msgs.AccelWithCovariance outobj = new geometry_msgs.AccelWithCovariance();
            outobj.accel = this.accel.Copy();
 
            outobj.covariance = new double[(int) 36];
            for (int a = 0; a < 36; a++) {
                outobj.covariance[a] = this.covariance[a];
            }
 
            return outobj;
        }
    }
}

