/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class InertiaStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Inertia inertia;
 
        public InertiaStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x3a39287c292abed7L;
 
        static InertiaStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.InertiaStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.InertiaStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Inertia._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.inertia._encodeRecursive(outs); 
 
        }
 
        public InertiaStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public InertiaStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.InertiaStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.InertiaStamped o = new geometry_msgs.InertiaStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.inertia = geometry_msgs.Inertia._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.InertiaStamped Copy()
        {
            geometry_msgs.InertiaStamped outobj = new geometry_msgs.InertiaStamped();
            outobj.header = this.header.Copy();
 
            outobj.inertia = this.inertia.Copy();
 
            return outobj;
        }
    }
}

