/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class PolygonStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Polygon polygon;
 
        public PolygonStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x413a2f753630b1d7L;
 
        static PolygonStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.PolygonStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.PolygonStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Polygon._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.polygon._encodeRecursive(outs); 
 
        }
 
        public PolygonStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PolygonStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.PolygonStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.PolygonStamped o = new geometry_msgs.PolygonStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.polygon = geometry_msgs.Polygon._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.PolygonStamped Copy()
        {
            geometry_msgs.PolygonStamped outobj = new geometry_msgs.PolygonStamped();
            outobj.header = this.header.Copy();
 
            outobj.polygon = this.polygon.Copy();
 
            return outobj;
        }
    }
}

