/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class PoseStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Pose pose;
 
        public PoseStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xe10feebec5c97663L;
 
        static PoseStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.PoseStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.PoseStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Pose._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.pose._encodeRecursive(outs); 
 
        }
 
        public PoseStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PoseStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.PoseStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.PoseStamped o = new geometry_msgs.PoseStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.PoseStamped Copy()
        {
            geometry_msgs.PoseStamped outobj = new geometry_msgs.PoseStamped();
            outobj.header = this.header.Copy();
 
            outobj.pose = this.pose.Copy();
 
            return outobj;
        }
    }
}

