/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class PoseWithCovarianceStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.PoseWithCovariance pose;
 
        public PoseWithCovarianceStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xe10feebec5c97663L;
 
        static PoseWithCovarianceStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.PoseWithCovarianceStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.PoseWithCovarianceStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.PoseWithCovariance._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.pose._encodeRecursive(outs); 
 
        }
 
        public PoseWithCovarianceStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PoseWithCovarianceStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.PoseWithCovarianceStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.PoseWithCovarianceStamped o = new geometry_msgs.PoseWithCovarianceStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.pose = geometry_msgs.PoseWithCovariance._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.PoseWithCovarianceStamped Copy()
        {
            geometry_msgs.PoseWithCovarianceStamped outobj = new geometry_msgs.PoseWithCovarianceStamped();
            outobj.header = this.header.Copy();
 
            outobj.pose = this.pose.Copy();
 
            return outobj;
        }
    }
}

