/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class PoseArray : LCM.LCM.LCMEncodable
    {
        public int poses_length;
        public std_msgs.Header header;
        public geometry_msgs.Pose[] poses;
 
        public PoseArray()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xc779b6acc503055aL;
 
        static PoseArray()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.PoseArray"))
                return 0L;
 
            classes.Add("geometry_msgs.PoseArray");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Pose._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.poses_length); 
 
            this.header._encodeRecursive(outs); 
 
            for (int a = 0; a < this.poses_length; a++) {
                this.poses[a]._encodeRecursive(outs); 
            }
 
        }
 
        public PoseArray(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PoseArray(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.PoseArray _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.PoseArray o = new geometry_msgs.PoseArray();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.poses_length = ins.ReadInt32();
 
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.poses = new geometry_msgs.Pose[(int) poses_length];
            for (int a = 0; a < this.poses_length; a++) {
                this.poses[a] = geometry_msgs.Pose._decodeRecursiveFactory(ins);
            }
 
        }
 
        public geometry_msgs.PoseArray Copy()
        {
            geometry_msgs.PoseArray outobj = new geometry_msgs.PoseArray();
            outobj.poses_length = this.poses_length;
 
            outobj.header = this.header.Copy();
 
            outobj.poses = new geometry_msgs.Pose[(int) poses_length];
            for (int a = 0; a < this.poses_length; a++) {
                outobj.poses[a] = this.poses[a].Copy();
            }
 
            return outobj;
        }
    }
}

