/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class QuaternionStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Quaternion quaternion;
 
        public QuaternionStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x7a3833b23af3ee48L;
 
        static QuaternionStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.QuaternionStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.QuaternionStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Quaternion._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.quaternion._encodeRecursive(outs); 
 
        }
 
        public QuaternionStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public QuaternionStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.QuaternionStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.QuaternionStamped o = new geometry_msgs.QuaternionStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.quaternion = geometry_msgs.Quaternion._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.QuaternionStamped Copy()
        {
            geometry_msgs.QuaternionStamped outobj = new geometry_msgs.QuaternionStamped();
            outobj.header = this.header.Copy();
 
            outobj.quaternion = this.quaternion.Copy();
 
            return outobj;
        }
    }
}

