/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class Transform : LCM.LCM.LCMEncodable
    {
        public geometry_msgs.Vector3 translation;
        public geometry_msgs.Quaternion rotation;
 
        public Transform()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x1275bd1ccbdaf47fL;
 
        static Transform()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.Transform"))
                return 0L;
 
            classes.Add("geometry_msgs.Transform");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Vector3._hashRecursive(classes)
                 + geometry_msgs.Quaternion._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.translation._encodeRecursive(outs); 
 
            this.rotation._encodeRecursive(outs); 
 
        }
 
        public Transform(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Transform(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.Transform _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.Transform o = new geometry_msgs.Transform();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.translation = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.rotation = geometry_msgs.Quaternion._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.Transform Copy()
        {
            geometry_msgs.Transform outobj = new geometry_msgs.Transform();
            outobj.translation = this.translation.Copy();
 
            outobj.rotation = this.rotation.Copy();
 
            return outobj;
        }
    }
}

