/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class TransformStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public String child_frame_id;
        public geometry_msgs.Transform transform;
 
        public TransformStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xf694f4a6d8779002L;
 
        static TransformStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.TransformStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.TransformStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Transform._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            this.header._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.child_frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            this.transform._encodeRecursive(outs); 
 
        }
 
        public TransformStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public TransformStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.TransformStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.TransformStamped o = new geometry_msgs.TransformStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.child_frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.transform = geometry_msgs.Transform._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.TransformStamped Copy()
        {
            geometry_msgs.TransformStamped outobj = new geometry_msgs.TransformStamped();
            outobj.header = this.header.Copy();
 
            outobj.child_frame_id = this.child_frame_id;
 
            outobj.transform = this.transform.Copy();
 
            return outobj;
        }
    }
}

