/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class TwistStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Twist twist;
 
        public TwistStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xf01245422c7b28c2L;
 
        static TwistStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.TwistStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.TwistStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Twist._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.twist._encodeRecursive(outs); 
 
        }
 
        public TwistStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public TwistStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.TwistStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.TwistStamped o = new geometry_msgs.TwistStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.twist = geometry_msgs.Twist._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.TwistStamped Copy()
        {
            geometry_msgs.TwistStamped outobj = new geometry_msgs.TwistStamped();
            outobj.header = this.header.Copy();
 
            outobj.twist = this.twist.Copy();
 
            return outobj;
        }
    }
}

