/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class Vector3Stamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Vector3 vector;
 
        public Vector3Stamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xecb8cfd985d1cbe0L;
 
        static Vector3Stamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.Vector3Stamped"))
                return 0L;
 
            classes.Add("geometry_msgs.Vector3Stamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Vector3._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.vector._encodeRecursive(outs); 
 
        }
 
        public Vector3Stamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Vector3Stamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.Vector3Stamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.Vector3Stamped o = new geometry_msgs.Vector3Stamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.vector = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.Vector3Stamped Copy()
        {
            geometry_msgs.Vector3Stamped outobj = new geometry_msgs.Vector3Stamped();
            outobj.header = this.header.Copy();
 
            outobj.vector = this.vector.Copy();
 
            return outobj;
        }
    }
}

