/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace geometry_msgs
{
    public sealed class WrenchStamped : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Wrench wrench;
 
        public WrenchStamped()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xecb7c2d77fc5d5e0L;
 
        static WrenchStamped()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("geometry_msgs.WrenchStamped"))
                return 0L;
 
            classes.Add("geometry_msgs.WrenchStamped");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Wrench._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.wrench._encodeRecursive(outs); 
 
        }
 
        public WrenchStamped(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public WrenchStamped(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static geometry_msgs.WrenchStamped _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            geometry_msgs.WrenchStamped o = new geometry_msgs.WrenchStamped();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.wrench = geometry_msgs.Wrench._decodeRecursiveFactory(ins);
 
        }
 
        public geometry_msgs.WrenchStamped Copy()
        {
            geometry_msgs.WrenchStamped outobj = new geometry_msgs.WrenchStamped();
            outobj.header = this.header.Copy();
 
            outobj.wrench = this.wrench.Copy();
 
            return outobj;
        }
    }
}

