/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class ColorRGBA : LCM.LCM.LCMEncodable
    {
        public float r;
        public float g;
        public float b;
        public float a;
 
        public ColorRGBA()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x3719400fc6e3011aL;
 
        static ColorRGBA()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.ColorRGBA"))
                return 0L;
 
            classes.Add("std_msgs.ColorRGBA");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.r); 
 
            outs.Write(this.g); 
 
            outs.Write(this.b); 
 
            outs.Write(this.a); 
 
        }
 
        public ColorRGBA(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ColorRGBA(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.ColorRGBA _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.ColorRGBA o = new std_msgs.ColorRGBA();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.r = ins.ReadSingle();
 
            this.g = ins.ReadSingle();
 
            this.b = ins.ReadSingle();
 
            this.a = ins.ReadSingle();
 
        }
 
        public std_msgs.ColorRGBA Copy()
        {
            std_msgs.ColorRGBA outobj = new std_msgs.ColorRGBA();
            outobj.r = this.r;
 
            outobj.g = this.g;
 
            outobj.b = this.b;
 
            outobj.a = this.a;
 
            return outobj;
        }
    }
}

