/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class Duration : LCM.LCM.LCMEncodable
    {
        public int sec;
        public int nsec;
 
        public Duration()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xde1d24a3a8ecb648L;
 
        static Duration()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.Duration"))
                return 0L;
 
            classes.Add("std_msgs.Duration");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.sec); 
 
            outs.Write(this.nsec); 
 
        }
 
        public Duration(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Duration(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.Duration _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.Duration o = new std_msgs.Duration();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.sec = ins.ReadInt32();
 
            this.nsec = ins.ReadInt32();
 
        }
 
        public std_msgs.Duration Copy()
        {
            std_msgs.Duration outobj = new std_msgs.Duration();
            outobj.sec = this.sec;
 
            outobj.nsec = this.nsec;
 
            return outobj;
        }
    }
}

