/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class Float32MultiArray : LCM.LCM.LCMEncodable
    {
        public int data_length;
        public std_msgs.MultiArrayLayout layout;
        public float[] data;
 
        public Float32MultiArray()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x7138323e2b24be12L;
 
        static Float32MultiArray()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.Float32MultiArray"))
                return 0L;
 
            classes.Add("std_msgs.Float32MultiArray");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.MultiArrayLayout._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.data_length); 
 
            this.layout._encodeRecursive(outs); 
 
            for (int a = 0; a < this.data_length; a++) {
                outs.Write(this.data[a]); 
            }
 
        }
 
        public Float32MultiArray(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Float32MultiArray(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.Float32MultiArray _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.Float32MultiArray o = new std_msgs.Float32MultiArray();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.data_length = ins.ReadInt32();
 
            this.layout = std_msgs.MultiArrayLayout._decodeRecursiveFactory(ins);
 
            this.data = new float[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                this.data[a] = ins.ReadSingle();
            }
 
        }
 
        public std_msgs.Float32MultiArray Copy()
        {
            std_msgs.Float32MultiArray outobj = new std_msgs.Float32MultiArray();
            outobj.data_length = this.data_length;
 
            outobj.layout = this.layout.Copy();
 
            outobj.data = new float[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                outobj.data[a] = this.data[a];
            }
 
            return outobj;
        }
    }
}

