/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class Header : LCM.LCM.LCMEncodable
    {
        public int seq;
        public std_msgs.Time stamp;
        public String frame_id;
 
        public Header()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xdbb33f5b4c19b8eaL;
 
        static Header()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.Header"))
                return 0L;
 
            classes.Add("std_msgs.Header");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Time._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.seq); 
 
            this.stamp._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
        }
 
        public Header(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Header(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.Header _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.Header o = new std_msgs.Header();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.seq = ins.ReadInt32();
 
            this.stamp = std_msgs.Time._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
        }
 
        public std_msgs.Header Copy()
        {
            std_msgs.Header outobj = new std_msgs.Header();
            outobj.seq = this.seq;
 
            outobj.stamp = this.stamp.Copy();
 
            outobj.frame_id = this.frame_id;
 
            return outobj;
        }
    }
}

