/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class MultiArrayLayout : LCM.LCM.LCMEncodable
    {
        public int dim_length;
        public std_msgs.MultiArrayDimension[] dim;
        public int data_offset;
 
        public MultiArrayLayout()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0bf4b5363481d321L;
 
        static MultiArrayLayout()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.MultiArrayLayout"))
                return 0L;
 
            classes.Add("std_msgs.MultiArrayLayout");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.MultiArrayDimension._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.dim_length); 
 
            for (int a = 0; a < this.dim_length; a++) {
                this.dim[a]._encodeRecursive(outs); 
            }
 
            outs.Write(this.data_offset); 
 
        }
 
        public MultiArrayLayout(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public MultiArrayLayout(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.MultiArrayLayout _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.MultiArrayLayout o = new std_msgs.MultiArrayLayout();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.dim_length = ins.ReadInt32();
 
            this.dim = new std_msgs.MultiArrayDimension[(int) dim_length];
            for (int a = 0; a < this.dim_length; a++) {
                this.dim[a] = std_msgs.MultiArrayDimension._decodeRecursiveFactory(ins);
            }
 
            this.data_offset = ins.ReadInt32();
 
        }
 
        public std_msgs.MultiArrayLayout Copy()
        {
            std_msgs.MultiArrayLayout outobj = new std_msgs.MultiArrayLayout();
            outobj.dim_length = this.dim_length;
 
            outobj.dim = new std_msgs.MultiArrayDimension[(int) dim_length];
            for (int a = 0; a < this.dim_length; a++) {
                outobj.dim[a] = this.dim[a].Copy();
            }
 
            outobj.data_offset = this.data_offset;
 
            return outobj;
        }
    }
}

