/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace std_msgs
{
    public sealed class MultiArrayDimension : LCM.LCM.LCMEncodable
    {
        public String label;
        public int size;
        public int stride;
 
        public MultiArrayDimension()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xcec1b9e9d868ef97L;
 
        static MultiArrayDimension()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("std_msgs.MultiArrayDimension"))
                return 0L;
 
            classes.Add("std_msgs.MultiArrayDimension");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.label); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.size); 
 
            outs.Write(this.stride); 
 
        }
 
        public MultiArrayDimension(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public MultiArrayDimension(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static std_msgs.MultiArrayDimension _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            std_msgs.MultiArrayDimension o = new std_msgs.MultiArrayDimension();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.label = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.size = ins.ReadInt32();
 
            this.stride = ins.ReadInt32();
 
        }
 
        public std_msgs.MultiArrayDimension Copy()
        {
            std_msgs.MultiArrayDimension outobj = new std_msgs.MultiArrayDimension();
            outobj.label = this.label;
 
            outobj.size = this.size;
 
            outobj.stride = this.stride;
 
            return outobj;
        }
    }
}

