/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace actionlib_msgs
{
    public sealed class GoalStatusArray : LCM.LCM.LCMEncodable
    {
        public int status_list_length;
        public std_msgs.Header header;
        public actionlib_msgs.GoalStatus[] status_list;
 
        public GoalStatusArray()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0f5c35b2e7eed0faL;
 
        static GoalStatusArray()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("actionlib_msgs.GoalStatusArray"))
                return 0L;
 
            classes.Add("actionlib_msgs.GoalStatusArray");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + actionlib_msgs.GoalStatus._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.status_list_length); 
 
            this.header._encodeRecursive(outs); 
 
            for (int a = 0; a < this.status_list_length; a++) {
                this.status_list[a]._encodeRecursive(outs); 
            }
 
        }
 
        public GoalStatusArray(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public GoalStatusArray(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static actionlib_msgs.GoalStatusArray _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            actionlib_msgs.GoalStatusArray o = new actionlib_msgs.GoalStatusArray();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.status_list_length = ins.ReadInt32();
 
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.status_list = new actionlib_msgs.GoalStatus[(int) status_list_length];
            for (int a = 0; a < this.status_list_length; a++) {
                this.status_list[a] = actionlib_msgs.GoalStatus._decodeRecursiveFactory(ins);
            }
 
        }
 
        public actionlib_msgs.GoalStatusArray Copy()
        {
            actionlib_msgs.GoalStatusArray outobj = new actionlib_msgs.GoalStatusArray();
            outobj.status_list_length = this.status_list_length;
 
            outobj.header = this.header.Copy();
 
            outobj.status_list = new actionlib_msgs.GoalStatus[(int) status_list_length];
            for (int a = 0; a < this.status_list_length; a++) {
                outobj.status_list[a] = this.status_list[a].Copy();
            }
 
            return outobj;
        }
    }
}

