/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace actionlib_msgs
{
    public sealed class GoalID : LCM.LCM.LCMEncodable
    {
        public std_msgs.Time stamp;
        public String id;
 
        public GoalID()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xef36683ef0767e95L;
 
        static GoalID()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("actionlib_msgs.GoalID"))
                return 0L;
 
            classes.Add("actionlib_msgs.GoalID");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Time._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            this.stamp._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
        }
 
        public GoalID(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public GoalID(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static actionlib_msgs.GoalID _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            actionlib_msgs.GoalID o = new actionlib_msgs.GoalID();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.stamp = std_msgs.Time._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
        }
 
        public actionlib_msgs.GoalID Copy()
        {
            actionlib_msgs.GoalID outobj = new actionlib_msgs.GoalID();
            outobj.stamp = this.stamp.Copy();
 
            outobj.id = this.id;
 
            return outobj;
        }
    }
}

