/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class ChannelFloat32 : LCM.LCM.LCMEncodable
    {
        public int values_length;
        public String name;
        public float[] values;
 
        public ChannelFloat32()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x8cbe448953ebf073L;
 
        static ChannelFloat32()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.ChannelFloat32"))
                return 0L;
 
            classes.Add("sensor_msgs.ChannelFloat32");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.values_length); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.name); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            for (int a = 0; a < this.values_length; a++) {
                outs.Write(this.values[a]); 
            }
 
        }
 
        public ChannelFloat32(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ChannelFloat32(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.ChannelFloat32 _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.ChannelFloat32 o = new sensor_msgs.ChannelFloat32();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.values_length = ins.ReadInt32();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.name = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.values = new float[(int) values_length];
            for (int a = 0; a < this.values_length; a++) {
                this.values[a] = ins.ReadSingle();
            }
 
        }
 
        public sensor_msgs.ChannelFloat32 Copy()
        {
            sensor_msgs.ChannelFloat32 outobj = new sensor_msgs.ChannelFloat32();
            outobj.values_length = this.values_length;
 
            outobj.name = this.name;
 
            outobj.values = new float[(int) values_length];
            for (int a = 0; a < this.values_length; a++) {
                outobj.values[a] = this.values[a];
            }
 
            return outobj;
        }
    }
}

