/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class FluidPressure : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public double fluid_pressure;
        public double variance;
 
        public FluidPressure()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x36b91af6b8f9d388L;
 
        static FluidPressure()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.FluidPressure"))
                return 0L;
 
            classes.Add("sensor_msgs.FluidPressure");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.fluid_pressure); 
 
            outs.Write(this.variance); 
 
        }
 
        public FluidPressure(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public FluidPressure(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.FluidPressure _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.FluidPressure o = new sensor_msgs.FluidPressure();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.fluid_pressure = ins.ReadDouble();
 
            this.variance = ins.ReadDouble();
 
        }
 
        public sensor_msgs.FluidPressure Copy()
        {
            sensor_msgs.FluidPressure outobj = new sensor_msgs.FluidPressure();
            outobj.header = this.header.Copy();
 
            outobj.fluid_pressure = this.fluid_pressure;
 
            outobj.variance = this.variance;
 
            return outobj;
        }
    }
}

