/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class Illuminance : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public double illuminance;
        public double variance;
 
        public Illuminance()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xdfb4b65ce9b1b524L;
 
        static Illuminance()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.Illuminance"))
                return 0L;
 
            classes.Add("sensor_msgs.Illuminance");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.illuminance); 
 
            outs.Write(this.variance); 
 
        }
 
        public Illuminance(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Illuminance(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.Illuminance _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.Illuminance o = new sensor_msgs.Illuminance();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.illuminance = ins.ReadDouble();
 
            this.variance = ins.ReadDouble();
 
        }
 
        public sensor_msgs.Illuminance Copy()
        {
            sensor_msgs.Illuminance outobj = new sensor_msgs.Illuminance();
            outobj.header = this.header.Copy();
 
            outobj.illuminance = this.illuminance;
 
            outobj.variance = this.variance;
 
            return outobj;
        }
    }
}

