/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class Image : LCM.LCM.LCMEncodable
    {
        public int data_length;
        public std_msgs.Header header;
        public int height;
        public int width;
        public String encoding;
        public byte is_bigendian;
        public int step;
        public byte[] data;
 
        public Image()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x79d36c21d3c16094L;
 
        static Image()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.Image"))
                return 0L;
 
            classes.Add("sensor_msgs.Image");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.data_length); 
 
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.height); 
 
            outs.Write(this.width); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.encoding); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.is_bigendian); 
 
            outs.Write(this.step); 
 
            for (int a = 0; a < this.data_length; a++) {
                outs.Write(this.data[a]); 
            }
 
        }
 
        public Image(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Image(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.Image _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.Image o = new sensor_msgs.Image();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.data_length = ins.ReadInt32();
 
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.height = ins.ReadInt32();
 
            this.width = ins.ReadInt32();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.encoding = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.is_bigendian = ins.ReadByte();
 
            this.step = ins.ReadInt32();
 
            this.data = new byte[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                this.data[a] = ins.ReadByte();
            }
 
        }
 
        public sensor_msgs.Image Copy()
        {
            sensor_msgs.Image outobj = new sensor_msgs.Image();
            outobj.data_length = this.data_length;
 
            outobj.header = this.header.Copy();
 
            outobj.height = this.height;
 
            outobj.width = this.width;
 
            outobj.encoding = this.encoding;
 
            outobj.is_bigendian = this.is_bigendian;
 
            outobj.step = this.step;
 
            outobj.data = new byte[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                outobj.data[a] = this.data[a];
            }
 
            return outobj;
        }
    }
}

