/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class Imu : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Quaternion orientation;
        public double[] orientation_covariance;
        public geometry_msgs.Vector3 angular_velocity;
        public double[] angular_velocity_covariance;
        public geometry_msgs.Vector3 linear_acceleration;
        public double[] linear_acceleration_covariance;
 
        public Imu()
        {
            orientation_covariance = new double[9];
            angular_velocity_covariance = new double[9];
            linear_acceleration_covariance = new double[9];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x55c1e238541325f6L;
 
        static Imu()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.Imu"))
                return 0L;
 
            classes.Add("sensor_msgs.Imu");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Quaternion._hashRecursive(classes)
                 + geometry_msgs.Vector3._hashRecursive(classes)
                 + geometry_msgs.Vector3._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            this.orientation._encodeRecursive(outs); 
 
            for (int a = 0; a < 9; a++) {
                outs.Write(this.orientation_covariance[a]); 
            }
 
            this.angular_velocity._encodeRecursive(outs); 
 
            for (int a = 0; a < 9; a++) {
                outs.Write(this.angular_velocity_covariance[a]); 
            }
 
            this.linear_acceleration._encodeRecursive(outs); 
 
            for (int a = 0; a < 9; a++) {
                outs.Write(this.linear_acceleration_covariance[a]); 
            }
 
        }
 
        public Imu(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Imu(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.Imu _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.Imu o = new sensor_msgs.Imu();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.orientation = geometry_msgs.Quaternion._decodeRecursiveFactory(ins);
 
            this.orientation_covariance = new double[(int) 9];
            for (int a = 0; a < 9; a++) {
                this.orientation_covariance[a] = ins.ReadDouble();
            }
 
            this.angular_velocity = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.angular_velocity_covariance = new double[(int) 9];
            for (int a = 0; a < 9; a++) {
                this.angular_velocity_covariance[a] = ins.ReadDouble();
            }
 
            this.linear_acceleration = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.linear_acceleration_covariance = new double[(int) 9];
            for (int a = 0; a < 9; a++) {
                this.linear_acceleration_covariance[a] = ins.ReadDouble();
            }
 
        }
 
        public sensor_msgs.Imu Copy()
        {
            sensor_msgs.Imu outobj = new sensor_msgs.Imu();
            outobj.header = this.header.Copy();
 
            outobj.orientation = this.orientation.Copy();
 
            outobj.orientation_covariance = new double[(int) 9];
            for (int a = 0; a < 9; a++) {
                outobj.orientation_covariance[a] = this.orientation_covariance[a];
            }
 
            outobj.angular_velocity = this.angular_velocity.Copy();
 
            outobj.angular_velocity_covariance = new double[(int) 9];
            for (int a = 0; a < 9; a++) {
                outobj.angular_velocity_covariance[a] = this.angular_velocity_covariance[a];
            }
 
            outobj.linear_acceleration = this.linear_acceleration.Copy();
 
            outobj.linear_acceleration_covariance = new double[(int) 9];
            for (int a = 0; a < 9; a++) {
                outobj.linear_acceleration_covariance[a] = this.linear_acceleration_covariance[a];
            }
 
            return outobj;
        }
    }
}

