/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class Joy : LCM.LCM.LCMEncodable
    {
        public int axes_length;
        public int buttons_length;
        public std_msgs.Header header;
        public float[] axes;
        public int[] buttons;
 
        public Joy()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x209d2c19077a692fL;
 
        static Joy()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.Joy"))
                return 0L;
 
            classes.Add("sensor_msgs.Joy");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.axes_length); 
 
            outs.Write(this.buttons_length); 
 
            this.header._encodeRecursive(outs); 
 
            for (int a = 0; a < this.axes_length; a++) {
                outs.Write(this.axes[a]); 
            }
 
            for (int a = 0; a < this.buttons_length; a++) {
                outs.Write(this.buttons[a]); 
            }
 
        }
 
        public Joy(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Joy(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.Joy _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.Joy o = new sensor_msgs.Joy();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.axes_length = ins.ReadInt32();
 
            this.buttons_length = ins.ReadInt32();
 
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.axes = new float[(int) axes_length];
            for (int a = 0; a < this.axes_length; a++) {
                this.axes[a] = ins.ReadSingle();
            }
 
            this.buttons = new int[(int) buttons_length];
            for (int a = 0; a < this.buttons_length; a++) {
                this.buttons[a] = ins.ReadInt32();
            }
 
        }
 
        public sensor_msgs.Joy Copy()
        {
            sensor_msgs.Joy outobj = new sensor_msgs.Joy();
            outobj.axes_length = this.axes_length;
 
            outobj.buttons_length = this.buttons_length;
 
            outobj.header = this.header.Copy();
 
            outobj.axes = new float[(int) axes_length];
            for (int a = 0; a < this.axes_length; a++) {
                outobj.axes[a] = this.axes[a];
            }
 
            outobj.buttons = new int[(int) buttons_length];
            for (int a = 0; a < this.buttons_length; a++) {
                outobj.buttons[a] = this.buttons[a];
            }
 
            return outobj;
        }
    }
}

