/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class JoyFeedback : LCM.LCM.LCMEncodable
    {
        public byte type;
        public byte id;
        public float intensity;
 
        public JoyFeedback()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x244b242f84e14215L;
 
        public const int TYPE_LED = 0;
        public const int TYPE_RUMBLE = 1;
        public const int TYPE_BUZZER = 2;

        static JoyFeedback()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.JoyFeedback"))
                return 0L;
 
            classes.Add("sensor_msgs.JoyFeedback");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.type); 
 
            outs.Write(this.id); 
 
            outs.Write(this.intensity); 
 
        }
 
        public JoyFeedback(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public JoyFeedback(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.JoyFeedback _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.JoyFeedback o = new sensor_msgs.JoyFeedback();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.type = ins.ReadByte();
 
            this.id = ins.ReadByte();
 
            this.intensity = ins.ReadSingle();
 
        }
 
        public sensor_msgs.JoyFeedback Copy()
        {
            sensor_msgs.JoyFeedback outobj = new sensor_msgs.JoyFeedback();
            outobj.type = this.type;
 
            outobj.id = this.id;
 
            outobj.intensity = this.intensity;
 
            return outobj;
        }
    }
}

