/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class NavSatStatus : LCM.LCM.LCMEncodable
    {
        public sbyte status;
        public short service;
 
        public NavSatStatus()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x76b236592075c1dbL;
 
        public const int STATUS_NO_FIX = -1;
        public const int STATUS_FIX = 0;
        public const int STATUS_SBAS_FIX = 1;
        public const int STATUS_GBAS_FIX = 2;
        public const int SERVICE_GPS = 1;
        public const int SERVICE_GLONASS = 2;
        public const int SERVICE_COMPASS = 4;
        public const int SERVICE_GALILEO = 8;

        static NavSatStatus()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.NavSatStatus"))
                return 0L;
 
            classes.Add("sensor_msgs.NavSatStatus");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.status); 
 
            outs.Write(this.service); 
 
        }
 
        public NavSatStatus(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public NavSatStatus(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.NavSatStatus _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.NavSatStatus o = new sensor_msgs.NavSatStatus();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.status = ins.ReadSByte();
 
            this.service = ins.ReadInt16();
 
        }
 
        public sensor_msgs.NavSatStatus Copy()
        {
            sensor_msgs.NavSatStatus outobj = new sensor_msgs.NavSatStatus();
            outobj.status = this.status;
 
            outobj.service = this.service;
 
            return outobj;
        }
    }
}

