/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class PointField : LCM.LCM.LCMEncodable
    {
        public String name;
        public int offset;
        public byte datatype;
        public int count;
 
        public PointField()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x702e0e03f04285d7L;
 
        public const int INT8 = 1;
        public const int UINT8 = 2;
        public const int INT16 = 3;
        public const int UINT16 = 4;
        public const int INT32 = 5;
        public const int UINT32 = 6;
        public const int FLOAT32 = 7;
        public const int FLOAT64 = 8;

        static PointField()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.PointField"))
                return 0L;
 
            classes.Add("sensor_msgs.PointField");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.name); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.offset); 
 
            outs.Write(this.datatype); 
 
            outs.Write(this.count); 
 
        }
 
        public PointField(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PointField(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.PointField _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.PointField o = new sensor_msgs.PointField();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.name = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.offset = ins.ReadInt32();
 
            this.datatype = ins.ReadByte();
 
            this.count = ins.ReadInt32();
 
        }
 
        public sensor_msgs.PointField Copy()
        {
            sensor_msgs.PointField outobj = new sensor_msgs.PointField();
            outobj.name = this.name;
 
            outobj.offset = this.offset;
 
            outobj.datatype = this.datatype;
 
            outobj.count = this.count;
 
            return outobj;
        }
    }
}

