/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class PointCloud : LCM.LCM.LCMEncodable
    {
        public int points_length;
        public int channels_length;
        public std_msgs.Header header;
        public geometry_msgs.Point32[] points;
        public sensor_msgs.ChannelFloat32[] channels;
 
        public PointCloud()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x3ff7dc99e345164eL;
 
        static PointCloud()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.PointCloud"))
                return 0L;
 
            classes.Add("sensor_msgs.PointCloud");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Point32._hashRecursive(classes)
                 + sensor_msgs.ChannelFloat32._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.points_length); 
 
            outs.Write(this.channels_length); 
 
            this.header._encodeRecursive(outs); 
 
            for (int a = 0; a < this.points_length; a++) {
                this.points[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.channels_length; a++) {
                this.channels[a]._encodeRecursive(outs); 
            }
 
        }
 
        public PointCloud(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PointCloud(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.PointCloud _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.PointCloud o = new sensor_msgs.PointCloud();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.points_length = ins.ReadInt32();
 
            this.channels_length = ins.ReadInt32();
 
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.points = new geometry_msgs.Point32[(int) points_length];
            for (int a = 0; a < this.points_length; a++) {
                this.points[a] = geometry_msgs.Point32._decodeRecursiveFactory(ins);
            }
 
            this.channels = new sensor_msgs.ChannelFloat32[(int) channels_length];
            for (int a = 0; a < this.channels_length; a++) {
                this.channels[a] = sensor_msgs.ChannelFloat32._decodeRecursiveFactory(ins);
            }
 
        }
 
        public sensor_msgs.PointCloud Copy()
        {
            sensor_msgs.PointCloud outobj = new sensor_msgs.PointCloud();
            outobj.points_length = this.points_length;
 
            outobj.channels_length = this.channels_length;
 
            outobj.header = this.header.Copy();
 
            outobj.points = new geometry_msgs.Point32[(int) points_length];
            for (int a = 0; a < this.points_length; a++) {
                outobj.points[a] = this.points[a].Copy();
            }
 
            outobj.channels = new sensor_msgs.ChannelFloat32[(int) channels_length];
            for (int a = 0; a < this.channels_length; a++) {
                outobj.channels[a] = this.channels[a].Copy();
            }
 
            return outobj;
        }
    }
}

