/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class RelativeHumidity : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public double relative_humidity;
        public double variance;
 
        public RelativeHumidity()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x1db00395f858f771L;
 
        static RelativeHumidity()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.RelativeHumidity"))
                return 0L;
 
            classes.Add("sensor_msgs.RelativeHumidity");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.relative_humidity); 
 
            outs.Write(this.variance); 
 
        }
 
        public RelativeHumidity(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public RelativeHumidity(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.RelativeHumidity _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.RelativeHumidity o = new sensor_msgs.RelativeHumidity();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.relative_humidity = ins.ReadDouble();
 
            this.variance = ins.ReadDouble();
 
        }
 
        public sensor_msgs.RelativeHumidity Copy()
        {
            sensor_msgs.RelativeHumidity outobj = new sensor_msgs.RelativeHumidity();
            outobj.header = this.header.Copy();
 
            outobj.relative_humidity = this.relative_humidity;
 
            outobj.variance = this.variance;
 
            return outobj;
        }
    }
}

