/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace sensor_msgs
{
    public sealed class Temperature : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public double temperature;
        public double variance;
 
        public Temperature()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x39cc1dc52d6ca13dL;
 
        static Temperature()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("sensor_msgs.Temperature"))
                return 0L;
 
            classes.Add("sensor_msgs.Temperature");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.header._encodeRecursive(outs); 
 
            outs.Write(this.temperature); 
 
            outs.Write(this.variance); 
 
        }
 
        public Temperature(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Temperature(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static sensor_msgs.Temperature _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            sensor_msgs.Temperature o = new sensor_msgs.Temperature();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.temperature = ins.ReadDouble();
 
            this.variance = ins.ReadDouble();
 
        }
 
        public sensor_msgs.Temperature Copy()
        {
            sensor_msgs.Temperature outobj = new sensor_msgs.Temperature();
            outobj.header = this.header.Copy();
 
            outobj.temperature = this.temperature;
 
            outobj.variance = this.variance;
 
            return outobj;
        }
    }
}

