/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace visualization_msgs
{
    public sealed class InteractiveMarkerInit : LCM.LCM.LCMEncodable
    {
        public int markers_length;
        public String server_id;
        public long seq_num;
        public visualization_msgs.InteractiveMarker[] markers;
 
        public InteractiveMarkerInit()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x0d2afaf11cff61d9L;
 
        static InteractiveMarkerInit()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("visualization_msgs.InteractiveMarkerInit"))
                return 0L;
 
            classes.Add("visualization_msgs.InteractiveMarkerInit");
            ulong hash = LCM_FINGERPRINT_BASE
                 + visualization_msgs.InteractiveMarker._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.markers_length); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.server_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            outs.Write(this.seq_num); 
 
            for (int a = 0; a < this.markers_length; a++) {
                this.markers[a]._encodeRecursive(outs); 
            }
 
        }
 
        public InteractiveMarkerInit(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public InteractiveMarkerInit(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static visualization_msgs.InteractiveMarkerInit _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            visualization_msgs.InteractiveMarkerInit o = new visualization_msgs.InteractiveMarkerInit();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.markers_length = ins.ReadInt32();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.server_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.seq_num = ins.ReadInt64();
 
            this.markers = new visualization_msgs.InteractiveMarker[(int) markers_length];
            for (int a = 0; a < this.markers_length; a++) {
                this.markers[a] = visualization_msgs.InteractiveMarker._decodeRecursiveFactory(ins);
            }
 
        }
 
        public visualization_msgs.InteractiveMarkerInit Copy()
        {
            visualization_msgs.InteractiveMarkerInit outobj = new visualization_msgs.InteractiveMarkerInit();
            outobj.markers_length = this.markers_length;
 
            outobj.server_id = this.server_id;
 
            outobj.seq_num = this.seq_num;
 
            outobj.markers = new visualization_msgs.InteractiveMarker[(int) markers_length];
            for (int a = 0; a < this.markers_length; a++) {
                outobj.markers[a] = this.markers[a].Copy();
            }
 
            return outobj;
        }
    }
}

