/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace visualization_msgs
{
    public sealed class InteractiveMarkerPose : LCM.LCM.LCMEncodable
    {
        public std_msgs.Header header;
        public geometry_msgs.Pose pose;
        public String name;
 
        public InteractiveMarkerPose()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x8c873ae70410464dL;
 
        static InteractiveMarkerPose()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("visualization_msgs.InteractiveMarkerPose"))
                return 0L;
 
            classes.Add("visualization_msgs.InteractiveMarkerPose");
            ulong hash = LCM_FINGERPRINT_BASE
                 + std_msgs.Header._hashRecursive(classes)
                 + geometry_msgs.Pose._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            this.header._encodeRecursive(outs); 
 
            this.pose._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.name); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
        }
 
        public InteractiveMarkerPose(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public InteractiveMarkerPose(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static visualization_msgs.InteractiveMarkerPose _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            visualization_msgs.InteractiveMarkerPose o = new visualization_msgs.InteractiveMarkerPose();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.header = std_msgs.Header._decodeRecursiveFactory(ins);
 
            this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.name = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
        }
 
        public visualization_msgs.InteractiveMarkerPose Copy()
        {
            visualization_msgs.InteractiveMarkerPose outobj = new visualization_msgs.InteractiveMarkerPose();
            outobj.header = this.header.Copy();
 
            outobj.pose = this.pose.Copy();
 
            outobj.name = this.name;
 
            return outobj;
        }
    }
}

