/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace shape_msgs
{
    public sealed class MeshTriangle : LCM.LCM.LCMEncodable
    {
        public int[] vertex_indices;
 
        public MeshTriangle()
        {
            vertex_indices = new int[3];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x2ff7303a4eea918dL;
 
        static MeshTriangle()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("shape_msgs.MeshTriangle"))
                return 0L;
 
            classes.Add("shape_msgs.MeshTriangle");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 3; a++) {
                outs.Write(this.vertex_indices[a]); 
            }
 
        }
 
        public MeshTriangle(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public MeshTriangle(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static shape_msgs.MeshTriangle _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            shape_msgs.MeshTriangle o = new shape_msgs.MeshTriangle();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.vertex_indices = new int[(int) 3];
            for (int a = 0; a < 3; a++) {
                this.vertex_indices[a] = ins.ReadInt32();
            }
 
        }
 
        public shape_msgs.MeshTriangle Copy()
        {
            shape_msgs.MeshTriangle outobj = new shape_msgs.MeshTriangle();
            outobj.vertex_indices = new int[(int) 3];
            for (int a = 0; a < 3; a++) {
                outobj.vertex_indices[a] = this.vertex_indices[a];
            }
 
            return outobj;
        }
    }
}

