/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace shape_msgs
{
    public sealed class Plane : LCM.LCM.LCMEncodable
    {
        public double[] coef;
 
        public Plane()
        {
            coef = new double[4];
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x7e294b30ea2123f2L;
 
        static Plane()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("shape_msgs.Plane"))
                return 0L;
 
            classes.Add("shape_msgs.Plane");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            for (int a = 0; a < 4; a++) {
                outs.Write(this.coef[a]); 
            }
 
        }
 
        public Plane(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Plane(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static shape_msgs.Plane _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            shape_msgs.Plane o = new shape_msgs.Plane();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.coef = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                this.coef[a] = ins.ReadDouble();
            }
 
        }
 
        public shape_msgs.Plane Copy()
        {
            shape_msgs.Plane outobj = new shape_msgs.Plane();
            outobj.coef = new double[(int) 4];
            for (int a = 0; a < 4; a++) {
                outobj.coef[a] = this.coef[a];
            }
 
            return outobj;
        }
    }
}

