/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class Color : LCM.LCM.LCMEncodable
    {
        public double r;
        public double g;
        public double b;
        public double a;
 
        public Color()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x998136169753c441L;
 
        static Color()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.Color"))
                return 0L;
 
            classes.Add("foxglove_msgs.Color");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.r); 
 
            outs.Write(this.g); 
 
            outs.Write(this.b); 
 
            outs.Write(this.a); 
 
        }
 
        public Color(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Color(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.Color _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.Color o = new foxglove_msgs.Color();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.r = ins.ReadDouble();
 
            this.g = ins.ReadDouble();
 
            this.b = ins.ReadDouble();
 
            this.a = ins.ReadDouble();
 
        }
 
        public foxglove_msgs.Color Copy()
        {
            foxglove_msgs.Color outobj = new foxglove_msgs.Color();
            outobj.r = this.r;
 
            outobj.g = this.g;
 
            outobj.b = this.b;
 
            outobj.a = this.a;
 
            return outobj;
        }
    }
}

