/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class FrameTransform : LCM.LCM.LCMEncodable
    {
        public builtin_interfaces.Time timestamp;
        public String parent_frame_id;
        public String child_frame_id;
        public geometry_msgs.Vector3 translation;
        public geometry_msgs.Quaternion rotation;
 
        public FrameTransform()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x16cb223d6329d1f0L;
 
        static FrameTransform()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.FrameTransform"))
                return 0L;
 
            classes.Add("foxglove_msgs.FrameTransform");
            ulong hash = LCM_FINGERPRINT_BASE
                 + builtin_interfaces.Time._hashRecursive(classes)
                 + geometry_msgs.Vector3._hashRecursive(classes)
                 + geometry_msgs.Quaternion._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            this.timestamp._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.parent_frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.child_frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            this.translation._encodeRecursive(outs); 
 
            this.rotation._encodeRecursive(outs); 
 
        }
 
        public FrameTransform(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public FrameTransform(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.FrameTransform _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.FrameTransform o = new foxglove_msgs.FrameTransform();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.parent_frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.child_frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.translation = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.rotation = geometry_msgs.Quaternion._decodeRecursiveFactory(ins);
 
        }
 
        public foxglove_msgs.FrameTransform Copy()
        {
            foxglove_msgs.FrameTransform outobj = new foxglove_msgs.FrameTransform();
            outobj.timestamp = this.timestamp.Copy();
 
            outobj.parent_frame_id = this.parent_frame_id;
 
            outobj.child_frame_id = this.child_frame_id;
 
            outobj.translation = this.translation.Copy();
 
            outobj.rotation = this.rotation.Copy();
 
            return outobj;
        }
    }
}

