/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class LaserScan : LCM.LCM.LCMEncodable
    {
        public int ranges_length;
        public int intensities_length;
        public builtin_interfaces.Time timestamp;
        public String frame_id;
        public geometry_msgs.Pose pose;
        public double start_angle;
        public double end_angle;
        public double[] ranges;
        public double[] intensities;
 
        public LaserScan()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x22e7c769ba6a90c2L;
 
        static LaserScan()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.LaserScan"))
                return 0L;
 
            classes.Add("foxglove_msgs.LaserScan");
            ulong hash = LCM_FINGERPRINT_BASE
                 + builtin_interfaces.Time._hashRecursive(classes)
                 + geometry_msgs.Pose._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.ranges_length); 
 
            outs.Write(this.intensities_length); 
 
            this.timestamp._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            this.pose._encodeRecursive(outs); 
 
            outs.Write(this.start_angle); 
 
            outs.Write(this.end_angle); 
 
            for (int a = 0; a < this.ranges_length; a++) {
                outs.Write(this.ranges[a]); 
            }
 
            for (int a = 0; a < this.intensities_length; a++) {
                outs.Write(this.intensities[a]); 
            }
 
        }
 
        public LaserScan(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public LaserScan(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.LaserScan _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.LaserScan o = new foxglove_msgs.LaserScan();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.ranges_length = ins.ReadInt32();
 
            this.intensities_length = ins.ReadInt32();
 
            this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
            this.start_angle = ins.ReadDouble();
 
            this.end_angle = ins.ReadDouble();
 
            this.ranges = new double[(int) ranges_length];
            for (int a = 0; a < this.ranges_length; a++) {
                this.ranges[a] = ins.ReadDouble();
            }
 
            this.intensities = new double[(int) intensities_length];
            for (int a = 0; a < this.intensities_length; a++) {
                this.intensities[a] = ins.ReadDouble();
            }
 
        }
 
        public foxglove_msgs.LaserScan Copy()
        {
            foxglove_msgs.LaserScan outobj = new foxglove_msgs.LaserScan();
            outobj.ranges_length = this.ranges_length;
 
            outobj.intensities_length = this.intensities_length;
 
            outobj.timestamp = this.timestamp.Copy();
 
            outobj.frame_id = this.frame_id;
 
            outobj.pose = this.pose.Copy();
 
            outobj.start_angle = this.start_angle;
 
            outobj.end_angle = this.end_angle;
 
            outobj.ranges = new double[(int) ranges_length];
            for (int a = 0; a < this.ranges_length; a++) {
                outobj.ranges[a] = this.ranges[a];
            }
 
            outobj.intensities = new double[(int) intensities_length];
            for (int a = 0; a < this.intensities_length; a++) {
                outobj.intensities[a] = this.intensities[a];
            }
 
            return outobj;
        }
    }
}

