/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class ModelPrimitive : LCM.LCM.LCMEncodable
    {
        public int data_length;
        public geometry_msgs.Pose pose;
        public geometry_msgs.Vector3 scale;
        public foxglove_msgs.Color color;
        public bool override_color;
        public String url;
        public String media_type;
        public byte[] data;
 
        public ModelPrimitive()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x23cd41ba898fa1faL;
 
        static ModelPrimitive()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.ModelPrimitive"))
                return 0L;
 
            classes.Add("foxglove_msgs.ModelPrimitive");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Pose._hashRecursive(classes)
                 + geometry_msgs.Vector3._hashRecursive(classes)
                 + foxglove_msgs.Color._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.data_length); 
 
            this.pose._encodeRecursive(outs); 
 
            this.scale._encodeRecursive(outs); 
 
            this.color._encodeRecursive(outs); 
 
            outs.Write(this.override_color); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.url); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.media_type); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            for (int a = 0; a < this.data_length; a++) {
                outs.Write(this.data[a]); 
            }
 
        }
 
        public ModelPrimitive(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public ModelPrimitive(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.ModelPrimitive _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.ModelPrimitive o = new foxglove_msgs.ModelPrimitive();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.data_length = ins.ReadInt32();
 
            this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
            this.scale = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
            this.override_color = ins.ReadBoolean();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.url = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.media_type = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.data = new byte[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                this.data[a] = ins.ReadByte();
            }
 
        }
 
        public foxglove_msgs.ModelPrimitive Copy()
        {
            foxglove_msgs.ModelPrimitive outobj = new foxglove_msgs.ModelPrimitive();
            outobj.data_length = this.data_length;
 
            outobj.pose = this.pose.Copy();
 
            outobj.scale = this.scale.Copy();
 
            outobj.color = this.color.Copy();
 
            outobj.override_color = this.override_color;
 
            outobj.url = this.url;
 
            outobj.media_type = this.media_type;
 
            outobj.data = new byte[(int) data_length];
            for (int a = 0; a < this.data_length; a++) {
                outobj.data[a] = this.data[a];
            }
 
            return outobj;
        }
    }
}

