/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class Point2 : LCM.LCM.LCMEncodable
    {
        public double x;
        public double y;
 
        public Point2()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xd259512e30b44885L;
 
        static Point2()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.Point2"))
                return 0L;
 
            classes.Add("foxglove_msgs.Point2");
            ulong hash = LCM_FINGERPRINT_BASE
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.x); 
 
            outs.Write(this.y); 
 
        }
 
        public Point2(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public Point2(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.Point2 _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.Point2 o = new foxglove_msgs.Point2();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.x = ins.ReadDouble();
 
            this.y = ins.ReadDouble();
 
        }
 
        public foxglove_msgs.Point2 Copy()
        {
            foxglove_msgs.Point2 outobj = new foxglove_msgs.Point2();
            outobj.x = this.x;
 
            outobj.y = this.y;
 
            return outobj;
        }
    }
}

