/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class PointsAnnotation : LCM.LCM.LCMEncodable
    {
        public int points_length;
        public int outline_colors_length;
        public builtin_interfaces.Time timestamp;
        public byte type;
        public foxglove_msgs.Point2[] points;
        public foxglove_msgs.Color outline_color;
        public foxglove_msgs.Color[] outline_colors;
        public foxglove_msgs.Color fill_color;
        public double thickness;
 
        public PointsAnnotation()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x97465363cc7c2a18L;
 
        public const int UNKNOWN = 0;
        public const int POINTS = 1;
        public const int LINE_LOOP = 2;
        public const int LINE_STRIP = 3;
        public const int LINE_LIST = 4;

        static PointsAnnotation()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.PointsAnnotation"))
                return 0L;
 
            classes.Add("foxglove_msgs.PointsAnnotation");
            ulong hash = LCM_FINGERPRINT_BASE
                 + builtin_interfaces.Time._hashRecursive(classes)
                 + foxglove_msgs.Point2._hashRecursive(classes)
                 + foxglove_msgs.Color._hashRecursive(classes)
                 + foxglove_msgs.Color._hashRecursive(classes)
                 + foxglove_msgs.Color._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.points_length); 
 
            outs.Write(this.outline_colors_length); 
 
            this.timestamp._encodeRecursive(outs); 
 
            outs.Write(this.type); 
 
            for (int a = 0; a < this.points_length; a++) {
                this.points[a]._encodeRecursive(outs); 
            }
 
            this.outline_color._encodeRecursive(outs); 
 
            for (int a = 0; a < this.outline_colors_length; a++) {
                this.outline_colors[a]._encodeRecursive(outs); 
            }
 
            this.fill_color._encodeRecursive(outs); 
 
            outs.Write(this.thickness); 
 
        }
 
        public PointsAnnotation(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PointsAnnotation(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.PointsAnnotation _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.PointsAnnotation o = new foxglove_msgs.PointsAnnotation();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.points_length = ins.ReadInt32();
 
            this.outline_colors_length = ins.ReadInt32();
 
            this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
            this.type = ins.ReadByte();
 
            this.points = new foxglove_msgs.Point2[(int) points_length];
            for (int a = 0; a < this.points_length; a++) {
                this.points[a] = foxglove_msgs.Point2._decodeRecursiveFactory(ins);
            }
 
            this.outline_color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
            this.outline_colors = new foxglove_msgs.Color[(int) outline_colors_length];
            for (int a = 0; a < this.outline_colors_length; a++) {
                this.outline_colors[a] = foxglove_msgs.Color._decodeRecursiveFactory(ins);
            }
 
            this.fill_color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
            this.thickness = ins.ReadDouble();
 
        }
 
        public foxglove_msgs.PointsAnnotation Copy()
        {
            foxglove_msgs.PointsAnnotation outobj = new foxglove_msgs.PointsAnnotation();
            outobj.points_length = this.points_length;
 
            outobj.outline_colors_length = this.outline_colors_length;
 
            outobj.timestamp = this.timestamp.Copy();
 
            outobj.type = this.type;
 
            outobj.points = new foxglove_msgs.Point2[(int) points_length];
            for (int a = 0; a < this.points_length; a++) {
                outobj.points[a] = this.points[a].Copy();
            }
 
            outobj.outline_color = this.outline_color.Copy();
 
            outobj.outline_colors = new foxglove_msgs.Color[(int) outline_colors_length];
            for (int a = 0; a < this.outline_colors_length; a++) {
                outobj.outline_colors[a] = this.outline_colors[a].Copy();
            }
 
            outobj.fill_color = this.fill_color.Copy();
 
            outobj.thickness = this.thickness;
 
            return outobj;
        }
    }
}

