/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class PoseInFrame : LCM.LCM.LCMEncodable
    {
        public builtin_interfaces.Time timestamp;
        public String frame_id;
        public geometry_msgs.Pose pose;
 
        public PoseInFrame()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x84c6ef3a0a4c5cd6L;
 
        static PoseInFrame()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.PoseInFrame"))
                return 0L;
 
            classes.Add("foxglove_msgs.PoseInFrame");
            ulong hash = LCM_FINGERPRINT_BASE
                 + builtin_interfaces.Time._hashRecursive(classes)
                 + geometry_msgs.Pose._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            this.timestamp._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            this.pose._encodeRecursive(outs); 
 
        }
 
        public PoseInFrame(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public PoseInFrame(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.PoseInFrame _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.PoseInFrame o = new foxglove_msgs.PoseInFrame();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
        }
 
        public foxglove_msgs.PoseInFrame Copy()
        {
            foxglove_msgs.PoseInFrame outobj = new foxglove_msgs.PoseInFrame();
            outobj.timestamp = this.timestamp.Copy();
 
            outobj.frame_id = this.frame_id;
 
            outobj.pose = this.pose.Copy();
 
            return outobj;
        }
    }
}

