/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class SceneEntityDeletion : LCM.LCM.LCMEncodable
    {
        public builtin_interfaces.Time timestamp;
        public byte type;
        public String id;
 
        public SceneEntityDeletion()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xa6b01fa4694da548L;
 
        public const int MATCHING_ID = 0;
        public const int ALL = 1;

        static SceneEntityDeletion()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.SceneEntityDeletion"))
                return 0L;
 
            classes.Add("foxglove_msgs.SceneEntityDeletion");
            ulong hash = LCM_FINGERPRINT_BASE
                 + builtin_interfaces.Time._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            this.timestamp._encodeRecursive(outs); 
 
            outs.Write(this.type); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
        }
 
        public SceneEntityDeletion(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public SceneEntityDeletion(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.SceneEntityDeletion _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.SceneEntityDeletion o = new foxglove_msgs.SceneEntityDeletion();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
            this.type = ins.ReadByte();
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
        }
 
        public foxglove_msgs.SceneEntityDeletion Copy()
        {
            foxglove_msgs.SceneEntityDeletion outobj = new foxglove_msgs.SceneEntityDeletion();
            outobj.timestamp = this.timestamp.Copy();
 
            outobj.type = this.type;
 
            outobj.id = this.id;
 
            return outobj;
        }
    }
}

