/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class SceneEntity : LCM.LCM.LCMEncodable
    {
        public int metadata_length;
        public int arrows_length;
        public int cubes_length;
        public int spheres_length;
        public int cylinders_length;
        public int lines_length;
        public int triangles_length;
        public int texts_length;
        public int models_length;
        public builtin_interfaces.Time timestamp;
        public String frame_id;
        public String id;
        public builtin_interfaces.Duration lifetime;
        public bool frame_locked;
        public foxglove_msgs.KeyValuePair[] metadata;
        public foxglove_msgs.ArrowPrimitive[] arrows;
        public foxglove_msgs.CubePrimitive[] cubes;
        public foxglove_msgs.SpherePrimitive[] spheres;
        public foxglove_msgs.CylinderPrimitive[] cylinders;
        public foxglove_msgs.LinePrimitive[] lines;
        public foxglove_msgs.TriangleListPrimitive[] triangles;
        public foxglove_msgs.TextPrimitive[] texts;
        public foxglove_msgs.ModelPrimitive[] models;
 
        public SceneEntity()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xe143d679579f0ab0L;
 
        static SceneEntity()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.SceneEntity"))
                return 0L;
 
            classes.Add("foxglove_msgs.SceneEntity");
            ulong hash = LCM_FINGERPRINT_BASE
                 + builtin_interfaces.Time._hashRecursive(classes)
                 + builtin_interfaces.Duration._hashRecursive(classes)
                 + foxglove_msgs.KeyValuePair._hashRecursive(classes)
                 + foxglove_msgs.ArrowPrimitive._hashRecursive(classes)
                 + foxglove_msgs.CubePrimitive._hashRecursive(classes)
                 + foxglove_msgs.SpherePrimitive._hashRecursive(classes)
                 + foxglove_msgs.CylinderPrimitive._hashRecursive(classes)
                 + foxglove_msgs.LinePrimitive._hashRecursive(classes)
                 + foxglove_msgs.TriangleListPrimitive._hashRecursive(classes)
                 + foxglove_msgs.TextPrimitive._hashRecursive(classes)
                 + foxglove_msgs.ModelPrimitive._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            byte[] __strbuf = null;
            outs.Write(this.metadata_length); 
 
            outs.Write(this.arrows_length); 
 
            outs.Write(this.cubes_length); 
 
            outs.Write(this.spheres_length); 
 
            outs.Write(this.cylinders_length); 
 
            outs.Write(this.lines_length); 
 
            outs.Write(this.triangles_length); 
 
            outs.Write(this.texts_length); 
 
            outs.Write(this.models_length); 
 
            this.timestamp._encodeRecursive(outs); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.frame_id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            __strbuf = System.Text.Encoding.GetEncoding("US-ASCII").GetBytes(this.id); outs.Write(__strbuf.Length+1); outs.Write(__strbuf, 0, __strbuf.Length); outs.Write((byte) 0); 
 
            this.lifetime._encodeRecursive(outs); 
 
            outs.Write(this.frame_locked); 
 
            for (int a = 0; a < this.metadata_length; a++) {
                this.metadata[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.arrows_length; a++) {
                this.arrows[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.cubes_length; a++) {
                this.cubes[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.spheres_length; a++) {
                this.spheres[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.cylinders_length; a++) {
                this.cylinders[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.lines_length; a++) {
                this.lines[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.triangles_length; a++) {
                this.triangles[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.texts_length; a++) {
                this.texts[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.models_length; a++) {
                this.models[a]._encodeRecursive(outs); 
            }
 
        }
 
        public SceneEntity(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public SceneEntity(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.SceneEntity _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.SceneEntity o = new foxglove_msgs.SceneEntity();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            byte[] __strbuf = null;
            this.metadata_length = ins.ReadInt32();
 
            this.arrows_length = ins.ReadInt32();
 
            this.cubes_length = ins.ReadInt32();
 
            this.spheres_length = ins.ReadInt32();
 
            this.cylinders_length = ins.ReadInt32();
 
            this.lines_length = ins.ReadInt32();
 
            this.triangles_length = ins.ReadInt32();
 
            this.texts_length = ins.ReadInt32();
 
            this.models_length = ins.ReadInt32();
 
            this.timestamp = builtin_interfaces.Time._decodeRecursiveFactory(ins);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.frame_id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            __strbuf = new byte[ins.ReadInt32()-1]; ins.ReadFully(__strbuf); ins.ReadByte(); this.id = System.Text.Encoding.GetEncoding("US-ASCII").GetString(__strbuf);
 
            this.lifetime = builtin_interfaces.Duration._decodeRecursiveFactory(ins);
 
            this.frame_locked = ins.ReadBoolean();
 
            this.metadata = new foxglove_msgs.KeyValuePair[(int) metadata_length];
            for (int a = 0; a < this.metadata_length; a++) {
                this.metadata[a] = foxglove_msgs.KeyValuePair._decodeRecursiveFactory(ins);
            }
 
            this.arrows = new foxglove_msgs.ArrowPrimitive[(int) arrows_length];
            for (int a = 0; a < this.arrows_length; a++) {
                this.arrows[a] = foxglove_msgs.ArrowPrimitive._decodeRecursiveFactory(ins);
            }
 
            this.cubes = new foxglove_msgs.CubePrimitive[(int) cubes_length];
            for (int a = 0; a < this.cubes_length; a++) {
                this.cubes[a] = foxglove_msgs.CubePrimitive._decodeRecursiveFactory(ins);
            }
 
            this.spheres = new foxglove_msgs.SpherePrimitive[(int) spheres_length];
            for (int a = 0; a < this.spheres_length; a++) {
                this.spheres[a] = foxglove_msgs.SpherePrimitive._decodeRecursiveFactory(ins);
            }
 
            this.cylinders = new foxglove_msgs.CylinderPrimitive[(int) cylinders_length];
            for (int a = 0; a < this.cylinders_length; a++) {
                this.cylinders[a] = foxglove_msgs.CylinderPrimitive._decodeRecursiveFactory(ins);
            }
 
            this.lines = new foxglove_msgs.LinePrimitive[(int) lines_length];
            for (int a = 0; a < this.lines_length; a++) {
                this.lines[a] = foxglove_msgs.LinePrimitive._decodeRecursiveFactory(ins);
            }
 
            this.triangles = new foxglove_msgs.TriangleListPrimitive[(int) triangles_length];
            for (int a = 0; a < this.triangles_length; a++) {
                this.triangles[a] = foxglove_msgs.TriangleListPrimitive._decodeRecursiveFactory(ins);
            }
 
            this.texts = new foxglove_msgs.TextPrimitive[(int) texts_length];
            for (int a = 0; a < this.texts_length; a++) {
                this.texts[a] = foxglove_msgs.TextPrimitive._decodeRecursiveFactory(ins);
            }
 
            this.models = new foxglove_msgs.ModelPrimitive[(int) models_length];
            for (int a = 0; a < this.models_length; a++) {
                this.models[a] = foxglove_msgs.ModelPrimitive._decodeRecursiveFactory(ins);
            }
 
        }
 
        public foxglove_msgs.SceneEntity Copy()
        {
            foxglove_msgs.SceneEntity outobj = new foxglove_msgs.SceneEntity();
            outobj.metadata_length = this.metadata_length;
 
            outobj.arrows_length = this.arrows_length;
 
            outobj.cubes_length = this.cubes_length;
 
            outobj.spheres_length = this.spheres_length;
 
            outobj.cylinders_length = this.cylinders_length;
 
            outobj.lines_length = this.lines_length;
 
            outobj.triangles_length = this.triangles_length;
 
            outobj.texts_length = this.texts_length;
 
            outobj.models_length = this.models_length;
 
            outobj.timestamp = this.timestamp.Copy();
 
            outobj.frame_id = this.frame_id;
 
            outobj.id = this.id;
 
            outobj.lifetime = this.lifetime.Copy();
 
            outobj.frame_locked = this.frame_locked;
 
            outobj.metadata = new foxglove_msgs.KeyValuePair[(int) metadata_length];
            for (int a = 0; a < this.metadata_length; a++) {
                outobj.metadata[a] = this.metadata[a].Copy();
            }
 
            outobj.arrows = new foxglove_msgs.ArrowPrimitive[(int) arrows_length];
            for (int a = 0; a < this.arrows_length; a++) {
                outobj.arrows[a] = this.arrows[a].Copy();
            }
 
            outobj.cubes = new foxglove_msgs.CubePrimitive[(int) cubes_length];
            for (int a = 0; a < this.cubes_length; a++) {
                outobj.cubes[a] = this.cubes[a].Copy();
            }
 
            outobj.spheres = new foxglove_msgs.SpherePrimitive[(int) spheres_length];
            for (int a = 0; a < this.spheres_length; a++) {
                outobj.spheres[a] = this.spheres[a].Copy();
            }
 
            outobj.cylinders = new foxglove_msgs.CylinderPrimitive[(int) cylinders_length];
            for (int a = 0; a < this.cylinders_length; a++) {
                outobj.cylinders[a] = this.cylinders[a].Copy();
            }
 
            outobj.lines = new foxglove_msgs.LinePrimitive[(int) lines_length];
            for (int a = 0; a < this.lines_length; a++) {
                outobj.lines[a] = this.lines[a].Copy();
            }
 
            outobj.triangles = new foxglove_msgs.TriangleListPrimitive[(int) triangles_length];
            for (int a = 0; a < this.triangles_length; a++) {
                outobj.triangles[a] = this.triangles[a].Copy();
            }
 
            outobj.texts = new foxglove_msgs.TextPrimitive[(int) texts_length];
            for (int a = 0; a < this.texts_length; a++) {
                outobj.texts[a] = this.texts[a].Copy();
            }
 
            outobj.models = new foxglove_msgs.ModelPrimitive[(int) models_length];
            for (int a = 0; a < this.models_length; a++) {
                outobj.models[a] = this.models[a].Copy();
            }
 
            return outobj;
        }
    }
}

