/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class SceneUpdate : LCM.LCM.LCMEncodable
    {
        public int deletions_length;
        public int entities_length;
        public foxglove_msgs.SceneEntityDeletion[] deletions;
        public foxglove_msgs.SceneEntity[] entities;
 
        public SceneUpdate()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0x8f9d4ee9e2a92d31L;
 
        static SceneUpdate()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.SceneUpdate"))
                return 0L;
 
            classes.Add("foxglove_msgs.SceneUpdate");
            ulong hash = LCM_FINGERPRINT_BASE
                 + foxglove_msgs.SceneEntityDeletion._hashRecursive(classes)
                 + foxglove_msgs.SceneEntity._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            outs.Write(this.deletions_length); 
 
            outs.Write(this.entities_length); 
 
            for (int a = 0; a < this.deletions_length; a++) {
                this.deletions[a]._encodeRecursive(outs); 
            }
 
            for (int a = 0; a < this.entities_length; a++) {
                this.entities[a]._encodeRecursive(outs); 
            }
 
        }
 
        public SceneUpdate(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public SceneUpdate(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.SceneUpdate _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.SceneUpdate o = new foxglove_msgs.SceneUpdate();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.deletions_length = ins.ReadInt32();
 
            this.entities_length = ins.ReadInt32();
 
            this.deletions = new foxglove_msgs.SceneEntityDeletion[(int) deletions_length];
            for (int a = 0; a < this.deletions_length; a++) {
                this.deletions[a] = foxglove_msgs.SceneEntityDeletion._decodeRecursiveFactory(ins);
            }
 
            this.entities = new foxglove_msgs.SceneEntity[(int) entities_length];
            for (int a = 0; a < this.entities_length; a++) {
                this.entities[a] = foxglove_msgs.SceneEntity._decodeRecursiveFactory(ins);
            }
 
        }
 
        public foxglove_msgs.SceneUpdate Copy()
        {
            foxglove_msgs.SceneUpdate outobj = new foxglove_msgs.SceneUpdate();
            outobj.deletions_length = this.deletions_length;
 
            outobj.entities_length = this.entities_length;
 
            outobj.deletions = new foxglove_msgs.SceneEntityDeletion[(int) deletions_length];
            for (int a = 0; a < this.deletions_length; a++) {
                outobj.deletions[a] = this.deletions[a].Copy();
            }
 
            outobj.entities = new foxglove_msgs.SceneEntity[(int) entities_length];
            for (int a = 0; a < this.entities_length; a++) {
                outobj.entities[a] = this.entities[a].Copy();
            }
 
            return outobj;
        }
    }
}

