/* LCM type definition class file
 * This file was automatically generated by lcm-gen 1.5.1
 * DO NOT MODIFY BY HAND!!!!
 */

using System;
using System.Collections.Generic;
using System.IO;
using LCM.LCM;
 
namespace foxglove_msgs
{
    public sealed class SpherePrimitive : LCM.LCM.LCMEncodable
    {
        public geometry_msgs.Pose pose;
        public geometry_msgs.Vector3 size;
        public foxglove_msgs.Color color;
 
        public SpherePrimitive()
        {
        }
 
        public static readonly ulong LCM_FINGERPRINT;
        public static readonly ulong LCM_FINGERPRINT_BASE = 0xe7e8912ea6542887L;
 
        static SpherePrimitive()
        {
            LCM_FINGERPRINT = _hashRecursive(new List<String>());
        }
 
        public static ulong _hashRecursive(List<String> classes)
        {
            if (classes.Contains("foxglove_msgs.SpherePrimitive"))
                return 0L;
 
            classes.Add("foxglove_msgs.SpherePrimitive");
            ulong hash = LCM_FINGERPRINT_BASE
                 + geometry_msgs.Pose._hashRecursive(classes)
                 + geometry_msgs.Vector3._hashRecursive(classes)
                 + foxglove_msgs.Color._hashRecursive(classes)
                ;
            classes.RemoveAt(classes.Count - 1);
            return (hash<<1) + ((hash>>63)&1);
        }
 
        public void Encode(LCMDataOutputStream outs)
        {
            outs.Write((long) LCM_FINGERPRINT);
            _encodeRecursive(outs);
        }
 
        public void _encodeRecursive(LCMDataOutputStream outs)
        {
            this.pose._encodeRecursive(outs); 
 
            this.size._encodeRecursive(outs); 
 
            this.color._encodeRecursive(outs); 
 
        }
 
        public SpherePrimitive(byte[] data) : this(new LCMDataInputStream(data))
        {
        }
 
        public SpherePrimitive(LCMDataInputStream ins)
        {
            if ((ulong) ins.ReadInt64() != LCM_FINGERPRINT)
                throw new System.IO.IOException("LCM Decode error: bad fingerprint");
 
            _decodeRecursive(ins);
        }
 
        public static foxglove_msgs.SpherePrimitive _decodeRecursiveFactory(LCMDataInputStream ins)
        {
            foxglove_msgs.SpherePrimitive o = new foxglove_msgs.SpherePrimitive();
            o._decodeRecursive(ins);
            return o;
        }
 
        public void _decodeRecursive(LCMDataInputStream ins)
        {
            this.pose = geometry_msgs.Pose._decodeRecursiveFactory(ins);
 
            this.size = geometry_msgs.Vector3._decodeRecursiveFactory(ins);
 
            this.color = foxglove_msgs.Color._decodeRecursiveFactory(ins);
 
        }
 
        public foxglove_msgs.SpherePrimitive Copy()
        {
            foxglove_msgs.SpherePrimitive outobj = new foxglove_msgs.SpherePrimitive();
            outobj.pose = this.pose.Copy();
 
            outobj.size = this.size.Copy();
 
            outobj.color = this.color.Copy();
 
            return outobj;
        }
    }
}

